<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.1.2 (Python 3.7.4 on win32)" generated="20221005 17:10:04.861" rpa="false">
<suite id="s1" name="ValidateErrorMessage" source="D:\Python\TestProject\TestCases\ValidateErrorMessage.robot">
<test id="s1-t1" name="Validate Unsuccessful Login">
<kw name="fill the login form">
<arguments>
<arg>${user_name}</arg>
<arg>${valid_password}</arg>
</arguments>
<msg timestamp="20221005 17:10:05.287" level="FAIL">Variable '${valid_password}' not found. Did you mean:
    ${invalid_password}</msg>
<status status="FAIL" starttime="20221005 17:10:05.285" endtime="20221005 17:10:05.287"></status>
</kw>
<status status="FAIL" starttime="20221005 17:10:05.285" endtime="20221005 17:10:05.287" critical="yes">Variable '${valid_password}' not found. Did you mean:
    ${invalid_password}</status>
</test>
<status status="FAIL" starttime="20221005 17:10:04.863" endtime="20221005 17:10:05.290"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="ValidateErrorMessage">ValidateErrorMessage</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20221005 17:10:04.817" level="ERROR">Error in file 'D:\Python\TestProject\TestCases\ValidateErrorMessage.robot': Setting 'Documentation' used multiple times.</msg>
<msg timestamp="20221005 17:10:04.835" level="ERROR">Error in file 'D:\Python\TestProject\TestCases\ValidateErrorMessage.robot': Setting 'Test Setup' used multiple times.</msg>
<msg timestamp="20221005 17:10:04.843" level="ERROR">Error in file 'D:\Python\TestProject\TestCases\ValidateErrorMessage.robot': Setting 'Test Teardown' used multiple times.</msg>
<msg timestamp="20221005 17:10:05.272" level="ERROR">Error in file 'D:\Python\TestProject\TestCases\ValidateErrorMessage.robot': Resource file 'resources.robot' does not exist.</msg>
</errors>
</robot>
